### ISSUE TITLE
Idea: Add gangs and mechanic garages

### ISSUE THREAD

**Issue by AntMars008** [Omega248/os-policegarage#1]
How difficult will it be to add the ability to have garages for mechanics and gangs in the same script? Please let me know. This will surely make this a fire script!

**Comment by Omega248** [comment]
It would be easy to add things like, Ems, fire, mechanic and other jobs to it but gangs would require it to be more in depth with a connection to a database and then that gets into a different type of garage.

**Comment by Omega248** [comment]
I'm going to rework the entire garage to be a job garage instead of only police
